collections:
    - name: community.aws
      source: https://galaxy.ansible.com
    - name: amazon.aws
      source: https://galaxy.ansible.com
    - name: ansible.platform
      version: ">=2.5.0"
      source: https://galaxy.ansible.com
    - name: ansible.controller
      version: ">=4.6.0"
      source: https://galaxy.ansible.com
    - name: infra.aap_configuration
      version: ">=3.4.1"
      source: https://galaxy.ansible.com
